name: Test

on:
  [pull_request]


jobs:
  test:
    runs-on: ubuntu-latest
    environment: TEST
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Make test envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_TEST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
          
          file_name: .env.test
          fail_on_empty: true
      
      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_TEST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
          
          file_name: .env
          fail_on_empty: true

      - name: Test
        run: npm run ci:test

